課題提出
sato-koi/car_shop pull request #2
Opened 2019-01-06 13:48 UTC by sato-koi

コールバック作成まで完了致しました

2019-01-06 15:45 UTC, kazu-taka requested changes
1箇所コメントしましたので、確認お願いします！

2019-01-06 15:45 UTC, kazu-taka commented on app/views/cars/new.html.erb
> +  <h2 class="text-center"><%= t '.name' %></h2>
@sato-koi 
ここは`.name`だとタイトルが表示されないような気がします。
確認お願いします！

2019-01-07 01:33 UTC, sato-koi commented on app/views/cars/new.html.erb
> +  <h2 class="text-center"><%= t '.name' %></h2>
@kazu-taka 
修正してコミットし直しました。確認お願い致します

2019-01-07 05:04 UTC, kazu-taka approved these changes
@sato-koi 
問題ないのでマージします！

2019-01-07 05:05 UTC, merged