課題作成
sato-koi/car_shop pull request #5
Opened 2019-01-24 14:14 UTC by sato-koi

@kazu-taka 
お疲れ様です。ページネーション作成でエラーが出てしまいます。
index.html.erbの11行目がエラーとの表示で何度も確認しましたが解決できませんのでご確認お願い致します。

2019-01-24 14:21 UTC, sato-koi commented
![2019-01-24 23 19 57](https://user-images.githubusercontent.com/43980471/51684130-c5c33580-202e-11e9-905b-326e0a689e4a.png)

2019-01-24 14:31 UTC, sato-koi commented
@kazu-taka 
今度は別のエラーが出てきました！
![2019-01-24 23 29 15](https://user-images.githubusercontent.com/43980471/51684755-243ce380-2030-11e9-8617-c8113bf499eb.png)

2019-01-24 14:37 UTC, kazu-taka commented
@sato-koi 
エラーメッセージをよく見ていただくと、「Missing Template」と出ています。
つまり`_flash.html.erb`が存在しないというエラーになりますので、sharedディレクトリに該当のファイルが存在するか確認をお願いします:bow:

2019-01-28 16:04 UTC, kazu-taka requested changes

2019-01-28 16:04 UTC, kazu-taka commented on app/controllers/reviews_controller.rb
> +    @car = Car.find
@sato-koi 
`@car = Car.find`だけではエラーが発生するはずですが、登録画面は問題無く表示されますか？

2019-01-28 16:04 UTC, kazu-taka commented on app/controllers/reviews_controller.rb
> +    @review =Review.new(review_params)
@sato-koi 
イコールの後ろは半角スペースを入れるようにお願いします！

2019-01-28 16:04 UTC, kazu-taka commented on app/controllers/reviews_controller.rb
> +    @review =Review.find(params[:id])
@sato-koi 
こちらもイコールの後ろに半角スペースを入れるようにお願いします！

2019-01-28 16:04 UTC, kazu-taka commented on app/views/cars/show.html.erb
> +  <%= render partial: "reviews/review", collection: @book.reviews %>
@sato-koi 
`@book`は存在しないので確認お願いします。

2019-01-28 16:05 UTC, kazu-taka commented
@sato-koi 
プルリク作成前に動作確認は行って頂けてますか？
確実にエラーが発生すると思われる場所があったので、動作確認の方もお願いします:bow:

2019-01-30 17:23 UTC, merged